import unittest

from App.Application import Application
from App.communities_finder.CommunityCenter import CommunityCenter
from App.graph_builder.GraphBuilder import GraphBuilder
from App.tokenizer.TokenWizard import TokenWizard


class TestApplicationGlobal(unittest.TestCase):

    def helper_init_app_object(self):
        with open('C:/Users/HP2_STAT/Desktop/Git Projet/pudding/Test/test_application/test_resources/syntagms',
                  encoding="utf-8") as f:
            syntagms = f.readlines()
        tw = TokenWizard(syntagms, ["pomme de terre", "pommes de terre"], "fr_core_news_md")
        gb = GraphBuilder(tw.enchance_tokens())
        cc = CommunityCenter(gb.get_complete_graph())
        app = Application(tw, gb, cc)
        return app

    def test_global_application(self):
        output = self.helper_init_app_object().run()
        expected = [["J'",
                     "j'",
                     'Je',
                     'je',
                     'me',
                     'je',
                     "J'",
                     'je',
                     "J'",
                     'je',
                     'me',
                     'j’',
                     'je',
                     'je',
                     'je',
                     'je',
                     "j'",
                     'je',
                     'je',
                     'me',
                     'Je',
                     'je',
                     'j’',
                     'je',
                     'je',
                     "j'",
                     'je',
                     'me',
                     'j’',
                     'mon',
                     'je',
                     'moi',
                     "j'",
                     'je',
                     "j'",
                     'je',
                     'me',
                     'Je',
                     'je',
                     'Je'],
                    ['chaque'],
                    ['queue'],
                    ['voulu',
                     'pour',
                     'pour',
                     'pour',
                     'veux',
                     'dois',
                     'pour',
                     'voulu',
                     'pour',
                     'pouvais',
                     'pour',
                     'pour',
                     'devais',
                     'pour',
                     'pu',
                     'pour',
                     'demande',
                     'demande',
                     'doit',
                     'fini',
                     'entend',
                     'songez',
                     'aimez',
                     'tiens',
                     'pour',
                     'censé',
                     'avant',
                     'avant',
                     'fini',
                     'pour',
                     'allez',
                     'souhaitant',
                     'pour',
                     'essaie',
                     'tiens',
                     'déconseille'],
                    ['une',
                     'la',
                     'la',
                     'la',
                     'cette',
                     'une',
                     'la',
                     'une',
                     'une',
                     'la',
                     'la',
                     'Une',
                     'grande',
                     'sa'],
                    ['fois', 'fois'],
                    ['formé'],
                    ['des',
                     'des',
                     'les',
                     'les',
                     'les',
                     'leurs',
                     'des',
                     'plusieurs',
                     'les',
                     'les',
                     'des',
                     'deux',
                     'deux',
                     'certains',
                     'ces',
                     'des',
                     'les',
                     'Les',
                     'des',
                     'les',
                     'les'],
                    ['achats', 'achats', 'achats'],
                    ['en', 'en', 'en', 'En', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en'],
                    ['dehors', 'Dans', 'dans'],
                    ['de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de',
                     'de'],
                    ["l'", "l'", "d'", "l'", "d'", "d'", 'l’', 'l’', 'l’', 'l’'],
                    ['épicerie', 'magasin', 'magasin', 'magasin'],
                    [',',
                     ',',
                     'et',
                     'et',
                     ',',
                     'malgré',
                     ',',
                     ',',
                     ',',
                     ',',
                     '.',
                     ',',
                     ',',
                     '.',
                     ',',
                     '.',
                     ',',
                     ',',
                     '.',
                     ',',
                     ',',
                     ',',
                     '.',
                     ',',
                     ',',
                     '.',
                     ',',
                     ',',
                     ',',
                     ',',
                     ',',
                     'comme',
                     ',',
                     ',',
                     '.',
                     ',',
                     'et',
                     ',',
                     ',',
                     '.',
                     ',',
                     ',',
                     'et',
                     ',',
                     '.',
                     'Cependant',
                     ',',
                     'et',
                     ',',
                     'et',
                     '.',
                     ',',
                     '.',
                     'et',
                     'et',
                     'comme',
                     'et',
                     '.',
                     'et',
                     ',',
                     'et',
                     '.',
                     ',',
                     'et',
                     ',',
                     ',',
                     '.',
                     ',',
                     '.',
                     '.'],
                    ['du',
                     'un',
                     'du',
                     'le',
                     'un',
                     'le',
                     'le',
                     'le',
                     'ce',
                     'au',
                     'du',
                     'le',
                     'le',
                     'le',
                     'ce',
                     'du',
                     'le',
                     'un',
                     'Le',
                     'le',
                     'le',
                     'un',
                     'un',
                     'le',
                     'ce',
                     'du',
                     'le',
                     'ce',
                     'le'],
                    ['rez-de-chaussée'],
                    ['collègue'],
                    ['samedi', 'matin', '15h', 'matin', '20h', 'dimanche', '19h20', 'hier'],
                    ['...', '!', '!', '!', '!', '!'],
                    ['\n ',
                     '\n ',
                     '\n ',
                     '\n ',
                     '\n ',
                     '\n ',
                     '\n ',
                     '\n ',
                     '\n ',
                     '\n ',
                     '\n ',
                     '\n '],
                    ['section',
                     'présence',
                     'expérience',
                     'fonctionnelle',
                     'sécurité',
                     'professionnel',
                     'réorientation',
                     'réapprovisionnement',
                     'qualité',
                     'marché',
                     'explications',
                     'réflexion',
                     'également',
                     'personnel',
                     'client',
                     'procédés',
                     'client',
                     'prioritaire'],
                    ['emballage', 'produit'],
                    ['carte'],
                    ['perdu', 'quitté', 'perdu', 'volé', 'volé'],
                    ['temps', 'temps', 'temps', 'temps'],
                    ['à', 'à', 'à', 'à', 'à', 'à', 'à'],
                    ['retours'],
                    ['prix', 'prix'],
                    ['car',
                     'tout',
                     'ne',
                     'pas',
                     'que',
                     'trop',
                     'comment',
                     'ailleurs',
                     'sentiment',
                     'que',
                     'aucun',
                     'problème',
                     'rien',
                     'ne',
                     'plus',
                     'précipitamment',
                     'ne',
                     'pas',
                     'presque',
                     'mais',
                     "aujourd'hui",
                     'très',
                     'mauvaise',
                     'Si',
                     'aucune',
                     'car',
                     'seulement',
                     'si',
                     'que',
                     'tout',
                     'plus',
                     'qui',
                     'aussi',
                     'pas',
                     'tout',
                     'si',
                     'pas',
                     'souvent',
                     'surtout',
                     'assez',
                     'sachant',
                     'que',
                     'si',
                     'pas',
                     'que',
                     'tout',
                     'même',
                     'bonne',
                     'surtout',
                     'super',
                     'déjà',
                     'disant',
                     'plus',
                     'peu',
                     'plus',
                     'très',
                     'ne',
                     'pas',
                     'qui',
                     'qui',
                     'très',
                     'quoi',
                     'alors',
                     'que',
                     'même',
                     'pas',
                     'toujours',
                     'pas',
                     'déjà',
                     'entendant',
                     'que',
                     'ne',
                     'même',
                     'pas',
                     'rendant',
                     "qu'",
                     'mais',
                     'très',
                     'tout',
                     'extrêmement',
                     'brusqué',
                     'ne',
                     'même',
                     'pas',
                     "lorsqu'",
                     'que',
                     'rien',
                     'Inadmissible',
                     'ne',
                     'même',
                     'pas',
                     'que',
                     'désagréable',
                     'quand',
                     'car',
                     'que',
                     'surtout',
                     'que'],
                    ['code', 'codes'],
                    ['sur', 'sur'],
                    ['articles', 'articles', 'articles'],
                    ['ai',
                     'ai',
                     'sont',
                     'a',
                     'être',
                     'a',
                     'avoir',
                     'a',
                     'ai',
                     'suis',
                     'avoir',
                     'ai',
                     'avoir',
                     'aurais',
                     'aurais',
                     'suis',
                     'étais',
                     'ai',
                     'a',
                     'a',
                     'sommes',
                     'a',
                     'ai',
                     'avoir',
                     'a',
                     'a',
                     'aurait',
                     'avais',
                     'suis',
                     'avaient',
                     'etaient',
                     'avais',
                     'trompaient',
                     'a',
                     'avaient',
                     'sont',
                     'étaient',
                     'ont',
                     'constataient',
                     'avions',
                     'a',
                     'suis'],
                    ['affichés'],
                    ['panneaux'],
                    ['Puis'],
                    ['passage', 'remontant'],
                    ['caisse', 'caisses', 'caisse', 'caisse', 'caisse', 'caisse', 'caisse'],
                    ['🤦', '\u200d', '♂', '️.'],
                    ['chèque'],
                    ['cadeau'],
                    ['malpolis'],
                    ["n'", 'n’', 'n’', 'n’', "n'"],
                    ['y', 'y', 'y'],
                    ['auto'],
                    ['soit'],
                    ['bête'],
                    ["C'", "c'"],
                    ['est', 'fut', 'est', 'est', 'est', 'est', 'est', 'est', 'est'],
                    ['vigile', 'vigile', 'vigile', 'vigile'],
                    ['Après'],
                    ['minutes'],
                    ['(', ')'],
                    ['avec', 'avec', 'avec', 'avec'],
                    ['hôtesse', 'Hôtesse'],
                    ['reproche'],
                    ['celà'],
                    ['Par'],
                    ['contre'],
                    ['mit'],
                    ['remis'],
                    ['mains'],
                    ['votre', 'vous'],
                    ['taché'],
                    ['marge'],
                    ['mes', 'mes', 'mes'],
                    ['100e'],
                    ['gare'],
                    ['bref'],
                    ['monde'],
                    ['0'],
                    ['étoile'],
                    ['venue'],
                    ['courses'],
                    ['prenant', 'prend', 'prend'],
                    ['espèce', 'espèce', 'espèce'],
                    ['genre'],
                    ['celui'],
                    ['ci'],
                    ['m’', 'm’'],
                    ['faire',
                     'faire',
                     'allers',
                     'connaître',
                     'trouver',
                     'utiliser',
                     'trouver',
                     'utiliser',
                     'transmettre',
                     'attendu',
                     'passer',
                     'attendre',
                     'navré',
                     'désolé',
                     'faire',
                     'précipiter',
                     'arriver',
                     'mettre',
                     'fait',
                     'faire',
                     'fais',
                     'ignore',
                     'régler',
                     'répond',
                     'poser',
                     'occuper',
                     'régler',
                     'ignore',
                     'dépend',
                     'souligner',
                     'comprend',
                     'sais',
                     'parler',
                     'fait',
                     'voler',
                     'excuser',
                     'excusant',
                     'fouiller',
                     'sortir',
                     'sortir',
                     'comprends',
                     'parler',
                     'fait',
                     'ignorer',
                     'discute',
                     'rappeler',
                     'payer'],
                    ['il', 'lui', 'il', 'il', 'on', 'il', 'il', 'on', 'lui', 'elle'],
                    ['haut', 'haut', 'bas'],
                    ['train'],
                    ['non'],
                    ['par'],
                    ['seconde'],
                    ['tard'],
                    ['s’', 's’', "s'", "s'", "s'"],
                    ['filles', 'jeunes'],
                    ['Agent'],
                    ['légal'],
                    ['social'],
                    ['Rayons', 'rayon'],
                    ['vides'],
                    ['aléatoires'],
                    ['point'],
                    ['ou'],
                    ['fruit'],
                    ['légume'],
                    ['plein'],
                    ['centre'],
                    ['ville'],
                    ['fermé', 'fermé', 'bloqué', 'bloquant'],
                    ['portes', 'portes'],
                    ['nous', 'nous', 'nous', 'nous'],
                    ['allés'],
                    ['excusaient'],
                    ['vigiles'],
                    ['sans'],
                    ['partir'],
                    ['10min', '40min'],
                    ['mal', 'mal', 'mal', 'mal'],
                    ['Apres'],
                    ['sorti'],
                    ['poli', 'poli'],
                    ['se', 'se', 'se'],
                    ['ticket'],
                    ['choqué'],
                    ['vigils', 'vigils'],
                    ['désagréables'],
                    ['sous'],
                    ['compte'],
                    ['ils', 'ils', 'ils'],
                    ['atteint'],
                    ['sommets']]
        self.assertEqual(expected, output)
