import unittest

from App.Application import Application
from App.communities_finder.CommunityCenter import CommunityCenter
from App.graph_builder.GraphBuilder import GraphBuilder
from App.tokenizer.TokenWizard import TokenWizard


class TestApplicationGlobal(unittest.TestCase):

    def helper_init_app_object(self):
        with open('C:/Users/HP2_STAT/Desktop/Git Projet/pudding/Test/test_application/test_resources/syntagms',
                  encoding="utf-8") as f:
            syntagms = f.readlines()
        tw = TokenWizard(syntagms, ["pomme de terre", "pommes de terre"], "fr_core_news_md")
        gb = GraphBuilder(tw.enchance_tokens())
        cc = CommunityCenter(gb.get_complete_graph())
        app = Application(tw, gb, cc)
        return app

    def test_global_application(self):
        output = self.helper_init_app_object().run()
        expected = [['voulu',
                     'veux',
                     'dois',
                     'voulu',
                     'pouvais',
                     'devais',
                     'aurais',
                     'aurais',
                     'fini',
                     'entend',
                     'songez',
                     'aimez',
                     'censé',
                     'fini',
                     'allez',
                     'essaie'],
                    ['fois', 'fois'],
                    ['légal'],
                    ['achats', 'achats', 'achats'],
                    ['épicerie', 'magasin', 'magasin', 'magasin'],
                    ['rez-de-chaussée'],
                    ['samedi', 'matin', 'matin', '20h', 'dimanche', '19h20', 'hier'],
                    ['demande', 'demande', 'souhaitant', 'déconseille'],
                    ['emballage', 'produit'],
                    ['carte'],
                    ['perdu', 'quitté', 'perdu', 'volé', 'volé'],
                    ['temps', 'temps', 'temps', 'temps'],
                    ['retours'],
                    ['prix', 'prix'],
                    ['code', 'codes'],
                    ['articles', 'articles', 'articles'],
                    ['affichés'],
                    ['panneaux'],
                    ['passage', 'remontant'],
                    ['caisse', 'caisses', 'caisse', 'caisse', 'caisse', 'caisse', 'caisse'],
                    ['\u200d', '♂', '️.'],
                    ['chèque'],
                    ['cadeau'],
                    ['auto'],
                    ['monde'],
                    ['bête'],
                    ['section',
                     'présence',
                     'trop',
                     'ailleurs',
                     'sentiment',
                     'problème',
                     'précipitamment',
                     'presque',
                     "aujourd'hui",
                     'mauvaise',
                     'expérience',
                     'prenant',
                     'fonctionnelle',
                     'sécurité',
                     'professionnel',
                     'réorientation',
                     'réapprovisionnement',
                     'bonne',
                     'qualité',
                     'marché',
                     'explications',
                     'prend',
                     'réflexion',
                     'prend',
                     'personnel',
                     'entendant',
                     'rendant',
                     'client',
                     'extrêmement',
                     'brusqué',
                     "lorsqu'",
                     'Inadmissible',
                     'procédés',
                     'désagréable',
                     'client',
                     'prioritaire'],
                    ['vigile', 'vigile', 'vigile', 'vigile'],
                    ['minutes'],
                    ['hôtesse', 'Hôtesse'],
                    ['reproche'],
                    ['genre'],
                    ['celà'],
                    ['contre'],
                    ['remis'],
                    ['mains'],
                    ['taché'],
                    ['marge'],
                    ['100e'],
                    ['gare'],
                    ['bref'],
                    ['fut'],
                    ['discute'],
                    ['0'],
                    ['étoile'],
                    ['venue'],
                    ['courses'],
                    ['collègue'],
                    ['espèce', 'espèce', 'espèce'],
                    ['train'],
                    ['navré',
                     'désolé',
                     'ignore',
                     'répond',
                     'sachant',
                     'ignore',
                     'dépend',
                     'disant',
                     'comprend',
                     'sais',
                     'excuser',
                     'excusant',
                     'comprends'],
                    ['faire',
                     'faire',
                     'allers',
                     'connaître',
                     'trouver',
                     'utiliser',
                     'trouver',
                     'utiliser',
                     'transmettre',
                     'passer',
                     'attendre',
                     'faire',
                     'précipiter',
                     'arriver',
                     'mettre',
                     'faire',
                     'régler',
                     'poser',
                     'occuper',
                     'régler',
                     'souligner',
                     'voler',
                     'fouiller',
                     'sortir',
                     'sortir',
                     'ignorer',
                     'rappeler',
                     'payer'],
                    ['haut', 'haut'],
                    ['non'],
                    ['seconde'],
                    ['tard'],
                    ['filles', 'jeunes'],
                    ['Agent'],
                    ['malpolis'],
                    ['social'],
                    ['Rayons', 'rayon'],
                    ['vides'],
                    ['aléatoires'],
                    ['point'],
                    ['fruit'],
                    ['légume'],
                    ['super'],
                    ['plein'],
                    ['centre'],
                    ['ville'],
                    ['fermé', 'fermé', 'bloqué', 'bloquant'],
                    ['portes', 'portes'],
                    ['sommes'],
                    ['allés'],
                    ['vigiles'],
                    ['partir'],
                    ['10min', '40min'],
                    ['mal', 'mal', 'mal', 'mal'],
                    ['sorti'],
                    ['poli', 'poli'],
                    ['ticket'],
                    ['choqué'],
                    ['désagréables'],
                    ['compte'],
                    ['trompaient', 'constataient'],
                    ['atteint'],
                    ['sommets'],
                    ['mit'],
                    ['avions'],
                    ['grande'],
                    ['queue'],
                    ['formé']]
        self.assertEqual(expected, output)
