import unittest

from pudding.App.Application import Application
from pudding.App.communities_finder.CommunityCenter import CommunityCenter
from pudding.App.graph_builder.GraphBuilder import GraphBuilder
from pudding.App.tokenizer.TokenWizard import TokenWizard


class TestApplicationGlobal(unittest.TestCase):

    def helper_init_app_object(self):
        with open('C:/Users/HP2_STAT/Desktop/Git Projet/pudding/pudding/Test/test_application/test_resources/syntagms',
                  encoding="utf-8") as f:
            syntagms = f.readlines()
        tw = TokenWizard(syntagms, ["pomme de terre", "pommes de terre"], "fr_core_news_md")
        gb = GraphBuilder(tw.enchance_tokens())
        cc = CommunityCenter(gb.get_complete_graph())
        app = Application(tw, gb, cc)
        return app

    def test_global_application(self):
        output = self.helper_init_app_object().run()
        expected = [['fois',
                     'temps',
                     'passage',
                     'trop',
                     'ailleurs',
                     'sentiment',
                     'problème',
                     'hôtesse',
                     'reproche',
                     'précipitamment',
                     'contre',
                     'fois',
                     'temps',
                     'presque',
                     'temps',
                     'temps',
                     "aujourd'hui",
                     'mauvaise',
                     'prenant',
                     'seconde',
                     'remontant',
                     'point',
                     'bonne',
                     'super',
                     'disant',
                     'partir',
                     'mal',
                     'mal',
                     'mal',
                     'mal',
                     'entendant',
                     'rendant',
                     'trompaient',
                     'sommets',
                     'grande',
                     'monde',
                     'malpolis',
                     'brusqué',
                     "lorsqu'",
                     'constataient',
                     'Hôtesse',
                     'désagréable'],
                    ['achats',
                     'section',
                     'emballage',
                     'retours',
                     'prix',
                     'présence',
                     'code',
                     'prix',
                     'articles',
                     'codes',
                     'articles',
                     'achats',
                     'expérience',
                     'fonctionnelle',
                     'demande',
                     'demande',
                     'non',
                     'articles',
                     'sécurité',
                     'professionnel',
                     'réorientation',
                     'social',
                     'vides',
                     'réapprovisionnement',
                     'aléatoires',
                     'qualité',
                     'marché',
                     'explications',
                     'achats',
                     'réflexion',
                     'produit',
                     'personnel',
                     'désagréables',
                     'client',
                     'souhaitant',
                     'extrêmement',
                     'Inadmissible',
                     'procédés',
                     'légal',
                     'client',
                     'prioritaire',
                     'déconseille'],
                    ['faire',
                     'faire',
                     'allers',
                     'connaître',
                     'trouver',
                     'utiliser',
                     'trouver',
                     'utiliser',
                     'transmettre',
                     'passer',
                     'attendre',
                     'faire',
                     'précipiter',
                     'arriver',
                     'mettre',
                     'faire',
                     'régler',
                     'poser',
                     'occuper',
                     'régler',
                     'souligner',
                     'voler',
                     'excuser',
                     'excusant',
                     'fouiller',
                     'sortir',
                     'sortir',
                     'ignorer',
                     'rappeler',
                     'payer'],
                    ['voulu',
                     'veux',
                     'dois',
                     'voulu',
                     'pouvais',
                     'navré',
                     'désolé',
                     'devais',
                     'bref',
                     'aurais',
                     'aurais',
                     'ignore',
                     'fini',
                     'entend',
                     'songez',
                     'aimez',
                     'sachant',
                     'ignore',
                     'censé',
                     'fini',
                     'sais',
                     'choqué',
                     'allez',
                     'comprends',
                     'essaie',
                     'train'],
                    ['épicerie',
                     'rez-de-chaussée',
                     'panneaux',
                     'caisse',
                     'caisses',
                     'caisse',
                     'caisse',
                     'mains',
                     'gare',
                     'courses',
                     'caisse',
                     'filles',
                     'Rayons',
                     'magasin',
                     'rayon',
                     'légume',
                     'centre',
                     'ville',
                     'magasin',
                     'portes',
                     'vigiles',
                     'caisse',
                     'jeunes',
                     'portes',
                     'magasin',
                     'caisse'],
                    ['perdu',
                     'quitté',
                     'perdu',
                     'fermé',
                     'fermé',
                     'sorti',
                     'volé',
                     'atteint',
                     'bloqué',
                     'bloquant',
                     'volé'],
                    ['samedi',
                     'matin',
                     'matin',
                     '20h',
                     'dimanche',
                     '19h20',
                     '10min',
                     '40min',
                     'hier'],
                    ['répond', 'dépend', 'comprend', 'prend', 'prend', 'discute'],
                    ['vigile', 'vigile', 'vigile', 'vigile'],
                    ['\u200d', '♂', '️.'],
                    ['espèce', 'espèce', 'espèce'],
                    ['chèque', 'ticket'],
                    ['bête', 'queue'],
                    ['venue', 'allés'],
                    ['haut', 'haut'],
                    ['sommes', 'avions'],
                    ['poli', 'poli'],
                    ['carte'],
                    ['affichés'],
                    ['cadeau'],
                    ['auto'],
                    ['minutes'],
                    ['celà'],
                    ['remis'],
                    ['taché'],
                    ['marge'],
                    ['100e'],
                    ['fut'],
                    ['0'],
                    ['étoile'],
                    ['tard'],
                    ['Agent'],
                    ['fruit'],
                    ['plein'],
                    ['compte'],
                    ['mit'],
                    ['formé'],
                    ['genre'],
                    ['collègue']]
        self.assertEqual(expected, output)
